spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasourse:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/transportation_service_database
    username: postgres
    password: 148868
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true
